strange-tiger/IG-2-Project

- Assets/Joker/CharacterSelectUIScripts/TempAccountDB.cs
- Assets/Joker/Scenes/Login_Joker.unity
- Assets/Joker/Scripts/FindPasswordUI.cs
- Assets/Joker/Scripts/LogInUI.cs
- Assets/Joker/Scripts/SignInUI.cs
- Assets/Scene/CharacterSelect.unity
- LogIn, CharacterSelect 씬 VR 상호작용 추가
- LogIn 씬 임시 데이터매니저 추가
> UI log in&char select vr joker

- Assets/Joker/CharacterSelectUIScripts/SelectCharacterUI.cs
- Assets/Joker/CharacterSelectUIScripts/TempAccountDB.cs
- Assets/Joker/Scenes/Login_Joker.unity
- Assets/Scene/CharacterSelect.unity
> UI char select connect db joker

- Assets/Joker/CharacterSelectUIScripts/DeletePopupUI.cs
- Assets/Plugins/Easy performant outline/Demo/Models for Demo scene/CartoonLowPolyCityLite/CartoonLowPolyCityLite_HDRP_2018.3.unitypackage.meta
- Assets/Plugins/Easy performant outline/Demo/Models for Demo scene/CartoonLowPolyCityLite/CartoonLowPolyCityLite_LWRP_2018.3.unitypackage.meta
- Assets/Plugins/Easy performant outline/Demo/Models for Demo scene/CartoonLowPolyCityLite/CartoonLowPolyCityLite_URP_2019.3.unitypackage.meta
- Assets/Resources/InitInsertAccountData.txt
- Assets/Resources/InitInsertAccountData.txt.meta
- Assets/Resources/Insert.txt
- Assets/Resources/InsertAccountInfo.txt
- Assets/Resources/InsertAccountInfo.txt.meta
- Assets/Scripts/MakeCharacterManager.cs
- Assets/Scripts/Util/DBUtil.cs
- Assets/Scripts/Util/MySqlEnum.cs
- 캐릭터 생성에서 ColorPicker 관련 사항 제거.
- DB 명 및 Column, Insert 방식 변경. (AccountInfoDB -> CharacterDB,
Json 형식으로 Insert 하던 것을 각각 Column에 추가.)
> [Fix] ColorPicker 제거 및 DB 변경

- Assets/Resources/InsertSocial.txt
- Assets/Resources/InsertSocial.txt.meta
- Assets/Resources/SelectSocialStatus.txt
- Assets/Resources/SelectSocialStatus.txt.meta
- Assets/Resources/UpdateSocialStatus.txt
- Assets/Resources/UpdateSocialStatus.txt.meta
- Assets/Scripts/Util/DBUtil.cs
- 요청 추가 함수.
- 요청의 상태를 확인하는 함수.
- 요청의 상태를 바꿔주는 함수.
> [Feat] RelationshipDB에 접근할 함수 추가_King

- Assets/Scripts/UI/LogIn/FindPasswordUI.cs
- Assets/Scripts/UI/LogIn/LogInUI.cs
- Assets/Scripts/UI/LogIn/SignInUI.cs
- Assets/Scripts/Util/DBUtil.cs
- Assets/Scripts/Util/MySqlEnum.cs
- DBUtil의 UpdateRelationship 관련 메소드 정리, 구현
> Util db util update relationship joker

- Assets/Scripts/Util/DBUtil.cs
- Unrequest 메서드 추가.
- CheckStateList 수정.
> [Fix] DBUtil 수정_King

- Assets/Scripts/Util/DBUtil.cs
- Online / Offline 여부 제외.
- IsLeft 추가
> [Fix] GetRelationList 수정_King

- Assets/01_Scripts/KeyboardManager.cs
> [Fix] 백스페이스 기능 에러 해결

- Assets/_ImportedAssets/Photon/PhotonUnityNetworking/Resources/PhotonServerSettings.asset
- Assets/_Scenes/Lobby1_Interaction_Test/ExpressionTest.unity
- Assets/_Scripts/LobbyAll/Feeling/RadialMenu.cs
- ProjectSettings/EditorBuildSettings.asset
- 동기화 Script 재구성.
- Player에게 UI를 추가하는 과정 Delayed. 
- 현재 동기화가 되지 않고 있음. -> Player마다 UI를 가지고 있지 않아서로 예상중.
- 이후, NewPlayer에 UI를 추가하고 다시 테스트 후 Fix 예정.
> [Repair] 감정표현 동기화 Repair_King

- Assets/_Scripts/LobbyAll/Feeling/RadialMenu.cs
- Assets/_Scripts/Util/DBUtil.cs
- IsThereRelationship 메서드에서 Query Syntax에 띄어쓰기 추가
> [Fix] DBUtil Fix_King

- Assets/_ImportedAssets/Photon/PhotonUnityNetworking/Resources/PhotonServerSettings.asset
- Assets/_Prefabs/Piano/PianoButton/PianoButton.prefab
- Assets/_Scenes/Lobby1_Interaction_Test/AbsolutePitch/Absolute Pitch.unity
- Assets/_Scripts/Lobby1_Interact/Piano/PianoButton.cs
1. OVRCameraRig에 Collider 붙여야 함
2. Photon 동기화 테스트 필요
3. NewPlayer에 Player태그 달아주기
> [Fix] PianoButton script 수정, RigidBody 추가

- Assets/Resources/NewPlayer.prefab
- Assets/Resources/OVRCameraRig.prefab
- Assets/_Scripts/Player/PlayerNetworking.cs
- Assets/_Scripts/UI/SoundPanel/VolumeController.cs
1. VolumeController script 수정
2. PlayerNetworking script 에 newPlayer AudioSource 할당
> [Fix] SoundSettingUI 수정

- Assets/ImportedAssets/Easy performant outline/Demo/Models for Demo scene/CartoonLowPolyCityLite/CartoonLowPolyCityLite_HDRP_2018.3.unitypackage.meta
- Assets/ImportedAssets/Easy performant outline/Demo/Models for Demo scene/CartoonLowPolyCityLite/CartoonLowPolyCityLite_LWRP_2018.3.unitypackage.meta
- Assets/ImportedAssets/Easy performant outline/Demo/Models for Demo scene/CartoonLowPolyCityLite/CartoonLowPolyCityLite_URP_2019.3.unitypackage.meta
- Assets/_ImportedAssets/Photon/PhotonUnityNetworking/Resources/PhotonServerSettings.asset
- PhotonServerSettings -> RPC 내역 추가.
- meta파일 정리.
> Sync betting_king

- Assets/_Materials/StartRoomFloor.mat
- Assets/_Materials/StartRoomFloor.mat.meta
- Assets/_Scenes/BuildScene/Login.unity
- Skybox에 _ImportedAssets\SkyBox Volume 2\DeepSpaceGreen\DSG 머테리얼 적용
- Login 씬 전용 바닥 머테리얼 StartRoomFloor.mat 생성
> [Add] Login 씬 skybox 추가 및 바닥 변경

- Assets/_Scripts/Lobby1_Interact/Piano/PianoButton.cs
1. 내부 구조 변경으로 인한 스크립트 수정
2. 사용하지 않는 주석 제거
> [Fix] 스크립트 수정

- Assets/_Scripts/Lobby2_Interact/WesternCampfire/Wood.cs
> [Feat] 사운드 쿨타임 추가

- Assets/_Scripts/PrivateRoom/SpawnDice.cs
- Assets/_Scripts/PrivateRoom/SpawnPaintbrush.cs
> [Fix] 더 이상 사용하지 않는 IPunObservable 삭제

- Assets/_Scripts/PrivateRoom/SpawnDice.cs
- Assets/_Scripts/PrivateRoom/SpawnPaintbrush.cs
- Assets/_Scripts/Util/DBUtil.cs
- Assets/_Scripts/Util/MySqlEnum.cs
- 펫의 상태, 레벨, 경험치, 착용 에셋, 사이즈 등을 List로 가져오는 GetPetInventory 구현
> [DB] GetPetInventory 구현.

- Assets/_Prefabs/Pets/Pet_Cat.prefab
- Assets/_Prefabs/Pets/Pet_Chicken.prefab
- Assets/_Prefabs/Pets/Pet_Crab.prefab
- Assets/_Prefabs/Pets/Pet_FlowerDryad.prefab
- Assets/_Prefabs/Pets/Pet_Ghost.prefab
- Assets/_Prefabs/Pets/Pet_Husky.prefab
- Assets/_Prefabs/Pets/Pet_Octopus.prefab
- Assets/_Prefabs/Pets/Pet_Plant.prefab
- Assets/_Prefabs/Pets/Pet_Puffe.prefab
- Assets/_Prefabs/Pets/Pet_Rabbit.prefab
- Assets/_Prefabs/Pets/Pet_Robot.prefab
- Assets/_Prefabs/Pets/Pet_Seed.prefab
- Assets/_Prefabs/Pets/Pet_Spore.prefab
- Assets/_Prefabs/Pets/Pet_Star.prefab
- Assets/_Prefabs/Pets/Pet_Tree.prefab
- Assets/_Prefabs/Pets/Pet_Turnipa.prefab
- Assets/_Scripts/LobbyAll/Pet/Pet.cs
- Assets/_Scripts/LobbyAll/Pet/Pet.cs.meta
> [Feat] Pet Prefabs 수정

- Assets/_Prefabs/Pets/Pet_Chicken.prefab
- Assets/_Prefabs/Pets/Pet_Crab.prefab
- Assets/_Prefabs/Pets/Pet_Ghost.prefab
- Assets/_Prefabs/Pets/Pet_Octopus.prefab
- Assets/_Prefabs/Pets/Pet_Plant.prefab
- Assets/_Prefabs/Pets/Pet_Puffe.prefab
- Assets/_Prefabs/Pets/Pet_Rabbit.prefab
- Assets/_Prefabs/Pets/Pet_Robot.prefab
- Assets/_Prefabs/Pets/Pet_Seed.prefab
- Assets/_Prefabs/Pets/Pet_Spore.prefab
- Assets/_Prefabs/Pets/Pet_Star.prefab
- Assets/_Prefabs/Pets/Pet_Tree.prefab
- Assets/_Prefabs/Pets/Pet_Turnipa.prefab
- Assets/_Scripts/LobbyAll/Pet/Pet.cs
- Prefab에 따라 사이즈 변경, 레벨 등을 확인할 수 있는 PetEvolutionCount 추가
> [Feat] PetEvolutionCount 추가

- Assets/_Prefabs/Pets/Pet_Cat.prefab
- Assets/_Prefabs/Pets/Pet_Chicken.prefab
- Assets/_Prefabs/Pets/Pet_Crab.prefab
- Assets/_Prefabs/Pets/Pet_FlowerDryad.prefab
- Assets/_Prefabs/Pets/Pet_Ghost.prefab
- Assets/_Prefabs/Pets/Pet_Husky.prefab
- Assets/_Prefabs/Pets/Pet_Octopus.prefab
- Assets/_Prefabs/Pets/Pet_Plant.prefab
- Assets/_Prefabs/Pets/Pet_Puffe.prefab
- Assets/_Prefabs/Pets/Pet_Rabbit.prefab
- Assets/_Prefabs/Pets/Pet_Robot.prefab
- Assets/_Prefabs/Pets/Pet_Seed.prefab
- Assets/_Prefabs/Pets/Pet_Spore.prefab
- Assets/_Prefabs/Pets/Pet_Star.prefab
- Assets/_Prefabs/Pets/Pet_Tree.prefab
- Assets/_Prefabs/Pets/Pet_Turnipa.prefab
- PetMove
- NavMeshAgent
- SphereCollider Trigger Radius 2
- Rigidbody NoUseGravity, Fix position&rotation
> [Fix] 프리팹에 PetMove 및 필요 컴포넌트 부착

- Assets/_Scripts/Util/CSVParser.cs
- Assets/_Scripts/Util/CSVParser.cs.meta
- CSV 파일 파싱을 위한 CSVParser 제작
- Util 폴더
- Assets.ParseCSV 네임스페이스, CSVParser 클래스, ParseCSV 함수
- 현재 string 값으로 이용할 수 있도록 구성
- 반환 값은 List<Dictionary<string, string>>, 키는 필드명
> [Feat] Util : CSVParser 제작

- Assets/_Scripts/Lobby2_Interact/FirstMoveAttack/FirstMoveAttackPlayer.cs
> [Fix] Script 수정

- Assets/Resources/OVRCameraRig.prefab
> [Fix] 카메라가 너무 가까이까지 볼 수 있던 오류 수정

- Assets/_Scripts/Lobby1_Interact/MiniBallGame/BallManager.cs
> [Fix] MineGameBall Ball 생성 안되던 버그 수정

- Assets/_Prefabs/PrivateRoom/PrivateRoomNPC/FantasyPrivateRoomNPC.prefab
- Assets/_Scenes/BuildScene/Login.unity
- Assets/_Scripts/LobbyAll/Pet/PetSpawner.cs
- Assets/_Scripts/UI/LogIn/ChangePassword/ChangePasswordUI.cs
- Assets/_Scripts/UI/LogIn/QuestionList.cs
- Assets/_Scripts/UI/LogIn/QuestionList.cs.meta
- Assets/_Scripts/UI/LogIn/SignInUI.cs
- Assets/_Scripts/UI/PetShop/PetUIManager.cs
- Assets/_Scripts/UI/PetShop/PurchaseUI.cs
- Assets/_Scripts/UI/PetShop/TransformUI.cs
- 로그인에서 드롭다운이 안보이는 문제를 스피너로 교체하여 해결
> Fix bug fix joker

- Assets/_Prefabs/PetShopNpc.prefab
- Assets/_Prefabs/UI/PetShop/PetShopCanvas.prefab
- Assets/_Scenes/BuildScene/Login.unity
- Assets/_Scripts/LobbyAll/Pet/PetShopInteract.cs
- Assets/_Scripts/UI/PetShop/PetShopPopup.cs
- Assets/_Scripts/UI/PetShop/PetUIManager.cs
- OutFocus를 하고 다시 OnFocus로 돌리지 않는 문제 해결
> [Fix] 펫 NPC 인터렉터블 관련 수정

- Assets/_Scripts/UI/PetShop/PetUIManager.cs
- 전체를 FindObjectsOfType으로 받고, 포톤뷰가 IsMine인 것을 찾아 닉네임을 받아온다.
> [Fix] PetUIManager에서 플레이어 네트워킹 받아오는 부분 수정

- Assets/_Prefabs/ShootingGame/NPC/Guidebook.prefab
- Assets/_Scenes/Lobby2_Interaction_Test/ShootingGame/Shooting_Waiting.unity
- Assets/_Scripts/ShootingGame/UI/GuideBook/GuideBookInteraction.cs
- Assets/_Scripts/ShootingGame/UI/GuideBook/GuideBookUIManager.cs
- 페이지가 나를 봄
- 소리가 남
- 서부 로비에서도 확인 가능
- 페이지가 이상하게 표시되지 않음
> [Fix] How To Play 디버깅 완료

- Assets/_Materials/DrunkenMaterial.mat
- Assets/_Scenes/BuildScene/Rooms/MakeCharacterRoom.unity
- Assets/_Sprites/_UI/MakeCharacter/MirrorTexture1.renderTexture
- Assets/_Sprites/_UI/MakeCharacter/MirrorTexture2.renderTexture
- 거울 위치 및 크기 변경.
- 거울의 화질 개선
- 거울 테두리 추가
> [Fix] 캐릭터 생성 방 수정

- Assets/_Scripts/Player/PlayerFocus.cs
- 이제 root가 아닌 중간에 있는 Focusable 오브젝트도 찾을 수 있음
> [Fix] 플레이어 포커스 로직 변경

- Assets/Resources/PrivateRoom/Dice.prefab
- Assets/_Prefabs/IsekaiObjectSlayer/Weapons/Sword1.prefab
- Assets/_Prefabs/IsekaiObjectSlayer/Weapons/Sword2.prefab
- Assets/_Prefabs/IsekaiObjectSlayer/Weapons/Sword3.prefab
- Assets/_Prefabs/IsekaiObjectSlayer/Weapons/Sword4.prefab
- Assets/_Prefabs/IsekaiObjectSlayer/Weapons/Sword5.prefab
- Assets/_Prefabs/IsekaiObjectSlayer/Weapons/Weapon1.prefab
- Assets/_Prefabs/IsekaiObjectSlayer/Weapons/Weapon2.prefab
- Assets/_Prefabs/IsekaiObjectSlayer/Weapons/Weapon3.prefab
- Assets/_Prefabs/IsekaiObjectSlayer/Weapons/Weapon4.prefab
- Assets/_Prefabs/IsekaiObjectSlayer/Weapons/Weapon5.prefab
- Assets/_Prefabs/IsekaiObjectSlayer/Weapons/Weapon6.prefab
- Assets/_Prefabs/IsekaiObjectSlayer/Weapons/Weapon7.prefab
- Assets/_Prefabs/IsekaiObjectSlayer/Weapons/Weapon8.prefab
- Assets/_Prefabs/PrivateRoom/Paintbrush/Legal_pad.prefab
- Assets/_Prefabs/PrivateRoom/Paintbrush/Pencil.prefab
- SyncOVRDistanceGrabbable로 잡을 오브젝트는 Object 레이어를 적용해야 한다.
> [Fix] 잡을 오브젝트 레이어 수정 -> Object

- Assets/_Scripts/Interaction/FocusableObjects.cs
- Assets/_Scripts/Interaction/FocusableObjectsSencer.cs
- Rigidbody 때문에 MeshCollider가 사라지던 문제 해결
- 다른 Focusable 컨포넌트가 있을 때 일어나는 오류 수정
> [Fix] 버그 픽스

- Assets/_Scripts/UI/LogIn/LogIn/LogInUI.cs
> [Feat] 로그인 시 온라인되어있는 계정은 더 로그인 할 수 없도록 블락

- Assets/_Scripts/Lobby1_Interact/IsekaiObjectSlayer/SummonCircle.cs
- Map / IsekaiObjectSlayer / IsekaiOne~Four / 소환진 5개, 무기 보관대 2개
> [Feat] 판타지 로비에 이세계 물건 베기 배치

- Assets/_Prefabs/PrivateRoom/PrivateRoomNPC/WesternPrivateRoomNPC.prefab
- Assets/_Scenes/BuildScene/Rooms/PrivateRoom.unity
- Assets/_Scripts/Keyboard/KeyboardManager.cs
- Assets/_Scripts/PrivateRoom/PrivateRoomExit.cs
- Assets/_Scripts/PrivateRoom/RoomDestroyer.cs
- Assets/_Scripts/StartRoom/LobbyChanger.cs
- Assets/_Scripts/UI/PrivateRoom/Create&Join/MakeRoomUI.cs
- ProjectSettings/ProjectSettings.asset
- 룸 삭제 부분 구현 완료
- 룸 입장 오류 : OutLinable 관련 오류와 연관이 있어보임, 협의 필요
> Private room bug fix joker

- Assets/_Scripts/Keyboard/KeyboardManager.cs
- 가상 키보드 한국어 입력 구현 완료
- 받침 입력, 이중자모음 구현 완료
> [Feat] 한국어 입력 구현 완료

- Assets/_Scripts/UI/MinerJ/CheckPoint.cs
- Assets/_Scripts/UI/MinerJ/HitPoint.cs
> Miner j repair ace

- Assets/_Scripts/Util/DBUtil.cs
- Assets/_Scripts/Util/MySqlEnum.cs
- 플레이어의 튜토리얼 수행 여부를 판단하는 메서드 추가.
- 플레이어의 튜토리얼 수행 여부 업데이트
> [Feat] 튜토리얼 DB 유틸 추가

- Assets/_Scripts/UI/PrivateRoom/Create&Join/JoinRoomUI.cs
- Page 수가 0이면 작동하지 않도록.
- 차후 체크 요망
> [Fix] ShowRoomList 관련 배열 크기 문제 수정

- Assets/_Scripts/Lobby2_Interact/WesternCampfire/Wood.cs
- 오류 사항 : 모래판에 넣으면 사라지고 그냥 땅에 놔야 안사라짐 (반대로 됨)
- 트리거 콜라이더의 태그에는 문제가 없음
- 동기화 부족으로 생각되어 수정
> [Fix] 캠프파이어 관련 오류 수정

- Assets/_Prefabs/dj/Pet.meta
- Assets/_Scripts/LobbyAll/Pet/Scriptable/TransformList.meta
- Assets/_Scripts/UI/PetShop/PetShopUIManager.cs
- PetShopUIManager에서 PetList 작성할 때 오류 발생
- PetProfile을 생성 전에 할당하려 해서 일어난 오류, 해결
- 로비 펫 NPC에 따른 다른 타이틀 적용, 배치
- 서버 연결과 함께 테스트 필요
> [Fix] 에러 수정 및 로비 펫 NPC 재배치

- Assets/_Scripts/UI/PetShop/PetEquipUI.cs
- Assets/_Scripts/UI/PetShop/PetPurchaseUI.cs
- RangeOut 문제 발생
- _currentIndex = -1의 경우가 예외 처리가 되지 않아 발생한 것으로 예상
- 수정, 테스트 필요
> [Fix] 코드 수정

- Assets/_Scripts/UI/PetShop/PetPurchaseUI.cs
- 이벤트 구독 과정에서 오류 발생
- 이벤트할 함수에 매개변수가 들어가지 않음
- 오버로딩을 통해 문제 해결
> [Fix] 이벤트 관련 문제 해결

- Assets/_Scripts/UI/PetShop/PetEquipUI.cs
- Assets/_Scripts/UI/PetShop/PetPurchaseUI.cs
- Assets/_Scripts/UI/PetShop/PetShopPopup.cs
- 한번 UI를 띄운 후 닫고 다시 하려고 하면 상호작용이 이루어지지 않는 문제 해결을 위한 코드 수정
> [Fix] NPC 한번 상호작용이 이루어진 다음 다시 상호작용이 이루어지지 않는 에러 수정

- Assets/_Scripts/UI/PrivateRoom/Create&Join/JoinRoom.cs
- FadeOut 코루틴 사용
- 딜레이 맞추도록 코루틴 같이 사용
> [Fix] FadeOut 딜레이 포함

- Assets/Resources/Pets/Pet_Cat.prefab
- Assets/Resources/Pets/Pet_Husky.prefab
- Assets/_Scripts/LobbyAll/Pet/PetLODMove.cs
- Assets/_Scripts/LobbyAll/Pet/PetLODMove.cs.meta
- Assets/_Scripts/LobbyAll/Pet/PetMove.cs
- 고양이, 허스키 에셋은 LODGroup을 적용하여 애니메이터가 여러 개
- 기존 PetMove는 하나의 애니메이터를 받기에 오류가 발생
- PetMove를 상속하고 복수의 애니메이터를 조절할 수 있는 PetLODMove를 작성하여 바꿔 넣음
- 테스트 필요
> [Fix] 펫 고양이, 허스키 애니메이터 오류 수정

- Assets/_Scripts/Util/DBUtil.cs
- DB Util 수정 사항이 적용이 되지 않았던 문제 해결
> [Fix] DBUtil 수정

- Assets/_Prefabs/Keyboard/KeyBoard_with_SpecialKeys_Korean.prefab
- EffectPlayer 적용
- 키보드 효과음 지정된 것 적용
- Button.onClick에 AudioSource.PlayOneShot 구독시켜 구현
> [Fix] 키보드 효과음 추가

- Assets/_Scripts/StartRoom/LobbyChanger.cs
- wantsToQuit을 이용해, DB를 업데이트하지 않으면 멈추게 함.
> [Fix] PlayerOnline 추가

- Assets/_Scripts/UI/SoundPanel/SoundManager.cs
- 판타지 로비 다리 메시콜라이더 적용
- SoundManager 수정 : Awake 부분
> [Fix] 판타지 로비 다리 메시콜라이더 적용 & SoundManager 수정

- Assets/_ImportedAssets/Photon/PhotonUnityNetworking/Resources/PhotonServerSettings.asset
- Assets/_Scenes/Lobby2_Interaction_Test/FirstMoveAttack.unity
- Assets/_Scripts/Interaction/FocusableObjects.cs
- Assets/_Scripts/Interaction/FocusableObjectsSencer.cs
> [Fix] 아웃라인 센서 오류 해결 실패

- Assets/_Scripts/Lobby1_Interact/IsekaiObjectSlayer/IsekaiObject.cs
- Assets/_Scripts/Lobby1_Interact/IsekaiObjectSlayer/IsekaiWeapon.cs
- 계산량이 너무 많아 최적화 수행
- IsekaiObject, IsekaiWeapon
> [Refac] 이세계 슬레이어 베기 기능 리팩토링

- Assets/_Prefabs/Lobby2Tutorial/Wood.prefab
- Assets/_Scenes/BuildScene/Rooms/TutorialRoom/Lobby2TutorialRoom.unity
- Assets/_Scripts/Interaction/FocusableObjects.cs
- 센서가 필요하지 않은 경우 인스팩터 창에서 설정하여 Sencer을 끌 수 있음
> [Fix] FocusableObjectSencer 방식 수정
